services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - app-network
  configs: {}


  database:
     image: postgres:latest
     environment:
       POSTGRES_DB: NotesHandlerDB
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: passwordi
       ports:

     volumes:
      - db-data:/var/lib/postgresql/data

networks:
  app-network: {}

volumes:
  db-data: {}
